// <auto-generated />
using System;
using ILD.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ILD.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613235425_AddCustomEdgeNameAndExternalActionEdgeName")]
    partial class AddCustomEdgeNameAndExternalActionEdgeName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ILD.Data.Entities.AdapterSessionSnapshot", b =>
                {
                    b.Property<Guid>("LoopRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SessionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LoopRunId", "AdapterName", "SessionId");

                    b.HasIndex("LoopRunId", "AdapterName");

                    b.ToTable("AdapterSessionSnapshots");
                });

            modelBuilder.Entity("ILD.Data.Entities.AiProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Config")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Parallelism")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("AiProviders");
                });

            modelBuilder.Entity("ILD.Data.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("ILD.Data.Entities.EventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LoopRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("RunNodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("LoopRunId", "Sequence");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("LoopTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoopTemplateVersionId");

                    b.ToTable("LoopNodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNodeEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EdgeType")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxTraversals")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetNodeId");

                    b.HasIndex("SourceNodeId", "TargetNodeId");

                    b.ToTable("LoopNodeEdges");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BranchName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedByLoopRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentAiSessionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("CurrentNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalActionEdgeName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalActionResult")
                        .HasColumnType("text");

                    b.Property<int>("ExternalActionResultType")
                        .HasColumnType("integer");

                    b.Property<string>("HumanFeedbackReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("IncomingEdgeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHalted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrMerged")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoopTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("NextEventSeq")
                        .HasColumnType("integer");

                    b.Property<int>("NodeExecutionCount")
                        .HasColumnType("integer");

                    b.Property<string>("PrUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("PreviousNodeOutput")
                        .HasColumnType("text");

                    b.Property<string>("RecoveryPolicy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Retain")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SteeringNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("LoopTemplateVersionId");

                    b.HasIndex("PrUrl");

                    b.HasIndex("Status");

                    b.HasIndex("WorkItemId");

                    b.ToTable("LoopRuns");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EffectiveInput")
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Guid?>("IncomingEdgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoopNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoopRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("NodeLabel")
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<Guid?>("PreviousNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoopNodeId");

                    b.HasIndex("LoopRunId");

                    b.HasIndex("Status");

                    b.ToTable("LoopRunNodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunSessionBinding", b =>
                {
                    b.Property<Guid>("LoopRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PlaceholderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LoopRunId", "AdapterName", "PlaceholderId");

                    b.HasIndex("LoopRunId", "AdapterName", "SessionId");

                    b.ToTable("LoopRunSessionBindings");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RecoveryPolicy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("LoopTemplates");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("LoopTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoopTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("LoopTemplateVersions");
                });

            modelBuilder.Entity("ILD.Data.Entities.RemoteProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("RemoteProviders");
                });

            modelBuilder.Entity("ILD.Data.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("DefaultIntakeStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RemoteProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorktreesPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RemoteProviderId");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("ILD.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SessionToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ILD.Data.Entities.AdapterSessionSnapshot", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany()
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.EventLog", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany("EventLogs")
                        .HasForeignKey("LoopRunId");

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNode", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopTemplateVersion", "LoopTemplateVersion")
                        .WithMany("Nodes")
                        .HasForeignKey("LoopTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopTemplateVersion");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNodeEdge", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopNode", "SourceNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ILD.Data.Entities.LoopNode", "TargetNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRun", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopTemplateVersion", "LoopTemplateVersion")
                        .WithMany("LoopRuns")
                        .HasForeignKey("LoopTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopTemplateVersion");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunNode", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopNode", "LoopNode")
                        .WithMany("RunNodes")
                        .HasForeignKey("LoopNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany("RunNodes")
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopNode");

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunSessionBinding", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany()
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplateVersion", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopTemplate", "LoopTemplate")
                        .WithMany("Versions")
                        .HasForeignKey("LoopTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopTemplate");
                });

            modelBuilder.Entity("ILD.Data.Entities.Repository", b =>
                {
                    b.HasOne("ILD.Data.Entities.RemoteProvider", "RemoteProvider")
                        .WithMany("Repositories")
                        .HasForeignKey("RemoteProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemoteProvider");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNode", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");

                    b.Navigation("RunNodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRun", b =>
                {
                    b.Navigation("EventLogs");

                    b.Navigation("RunNodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplateVersion", b =>
                {
                    b.Navigation("LoopRuns");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.RemoteProvider", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
