// <auto-generated />
using System;
using ILD.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ILD.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512161702_AddLoopRunSessionBindings")]
    partial class AddLoopRunSessionBindings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ILD.Data.Entities.AdapterSessionSnapshot", b =>
                {
                    b.Property<Guid>("LoopRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdapterName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SessionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("LoopRunId", "AdapterName", "SessionId");

                    b.HasIndex("LoopRunId", "AdapterName");

                    b.ToTable("AdapterSessionSnapshots");
                });

            modelBuilder.Entity("ILD.Data.Entities.AiProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("AiProviders");
                });

            modelBuilder.Entity("ILD.Data.Entities.EventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LoopRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RunNodeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("LoopRunId", "Sequence");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoopTemplateVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimeoutSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LoopTemplateVersionId");

                    b.ToTable("LoopNodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNodeEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EdgeType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxTraversals")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetNodeId");

                    b.HasIndex("SourceNodeId", "TargetNodeId");

                    b.ToTable("LoopNodeEdges");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedByLoopRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentNodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanFeedbackReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrMerged")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LoopTemplateVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NextEventSeq")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeExecutionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryPolicy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoopTemplateVersionId");

                    b.HasIndex("PrUrl");

                    b.HasIndex("Status");

                    b.HasIndex("WorkItemId");

                    b.ToTable("LoopRuns");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunEdgeTraversal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EdgeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoopRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TraversalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EdgeId");

                    b.HasIndex("LoopRunId", "EdgeId");

                    b.ToTable("LoopRunEdgeTraversals");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoopNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoopRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoopNodeId");

                    b.HasIndex("LoopRunId");

                    b.HasIndex("Status");

                    b.ToTable("LoopRunNodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunSessionBinding", b =>
                {
                    b.Property<Guid>("LoopRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdapterName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceholderId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("LoopRunId", "AdapterName", "PlaceholderId");

                    b.HasIndex("LoopRunId", "AdapterName", "SessionId");

                    b.ToTable("LoopRunSessionBindings");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxNodeExecutions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxWallClockHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryPolicy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("LoopTemplates");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("LoopTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoopTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("LoopTemplateVersions");
                });

            modelBuilder.Entity("ILD.Data.Entities.RemoteProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("GraceIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrentWorkItems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkItemApiKey")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkItemServerUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("RemoteProviders");
                });

            modelBuilder.Entity("ILD.Data.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultIntakeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RemoteProviderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreesPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RemoteProviderId");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("ILD.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ILD.Data.Entities.AdapterSessionSnapshot", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany()
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.EventLog", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany("EventLogs")
                        .HasForeignKey("LoopRunId");

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNode", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopTemplateVersion", "LoopTemplateVersion")
                        .WithMany("Nodes")
                        .HasForeignKey("LoopTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopTemplateVersion");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNodeEdge", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopNode", "SourceNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ILD.Data.Entities.LoopNode", "TargetNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRun", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopTemplateVersion", "LoopTemplateVersion")
                        .WithMany("LoopRuns")
                        .HasForeignKey("LoopTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopTemplateVersion");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunEdgeTraversal", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopNodeEdge", "Edge")
                        .WithMany("Traversals")
                        .HasForeignKey("EdgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany("EdgeTraversals")
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edge");

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunNode", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopNode", "LoopNode")
                        .WithMany("RunNodes")
                        .HasForeignKey("LoopNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany("RunNodes")
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopNode");

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunSessionBinding", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany()
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplateVersion", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopTemplate", "LoopTemplate")
                        .WithMany("Versions")
                        .HasForeignKey("LoopTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopTemplate");
                });

            modelBuilder.Entity("ILD.Data.Entities.Repository", b =>
                {
                    b.HasOne("ILD.Data.Entities.RemoteProvider", "RemoteProvider")
                        .WithMany("Repositories")
                        .HasForeignKey("RemoteProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemoteProvider");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNode", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");

                    b.Navigation("RunNodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNodeEdge", b =>
                {
                    b.Navigation("Traversals");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRun", b =>
                {
                    b.Navigation("EdgeTraversals");

                    b.Navigation("EventLogs");

                    b.Navigation("RunNodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplateVersion", b =>
                {
                    b.Navigation("LoopRuns");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.RemoteProvider", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
