// <auto-generated />
using System;
using ILD.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ILD.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009192004_EventLogPositionAsIdentityKey")]
    partial class EventLogPositionAsIdentityKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ILD.Data.Entities.AdapterSessionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("LoopRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SessionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId", "AdapterName", "SessionId")
                        .IsUnique();

                    b.HasIndex("LoopRunId", "AdapterName", "SessionId")
                        .IsUnique();

                    b.ToTable("AdapterSessionSnapshots");
                });

            modelBuilder.Entity("ILD.Data.Entities.AiProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Config")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Parallelism")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("AiProviders");
                });

            modelBuilder.Entity("ILD.Data.Entities.AiProviderTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AiProviderId");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("AiProviderTags");
                });

            modelBuilder.Entity("ILD.Data.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("ILD.Data.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Interrupted")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId", "Sequence");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ILD.Data.Entities.ChatSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiTag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ContinueChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ContinueSession")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("NextFireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PendingSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryIdsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryScope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Enabled", "NextFireAt");

                    b.ToTable("ChatSchedules");
                });

            modelBuilder.Entity("ILD.Data.Entities.ChatScheduleFiring", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("TurnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("Outcome");

                    b.HasIndex("TurnId");

                    b.HasIndex("ScheduleId", "Sequence")
                        .IsUnique();

                    b.ToTable("ChatScheduleFirings");
                });

            modelBuilder.Entity("ILD.Data.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentSessionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DeliveredBriefings")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastReadSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScratchPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("TitleSource")
                        .HasColumnType("integer");

                    b.Property<string>("ToolAllowlistCsv")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("ILD.Data.Entities.EventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Position");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("EdgeName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LoopRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("RunNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("LoopRunId", "Id");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("LoopTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoopTemplateVersionId");

                    b.ToTable("LoopNodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNodeEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EdgeType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetNodeId");

                    b.HasIndex("SourceNodeId", "TargetNodeId");

                    b.ToTable("LoopNodeEdges");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AiTraversalCount")
                        .HasColumnType("integer");

                    b.Property<string>("BaseBranchOverride")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedByLoopRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentAiSessionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("CurrentNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalActionEdgeName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalActionResult")
                        .HasColumnType("text");

                    b.Property<int>("ExternalActionResultType")
                        .HasColumnType("integer");

                    b.Property<int?>("HaltReason")
                        .HasColumnType("integer");

                    b.Property<string>("HumanFeedbackReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("IncomingEdgeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHalted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrMerged")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoopTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("NodeExecutionCount")
                        .HasColumnType("integer");

                    b.Property<string>("PrCommentLedger")
                        .HasColumnType("text");

                    b.Property<string>("PrCommentQueue")
                        .HasColumnType("text");

                    b.Property<string>("PrPolledEdgeStates")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PrSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("PrUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("PreviousNodeOutput")
                        .HasColumnType("text");

                    b.Property<string>("RecoveryPolicy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Retain")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SteeringNote")
                        .HasColumnType("text");

                    b.Property<int>("ThrottleAutoResumeCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ThrottleResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("LoopTemplateVersionId");

                    b.HasIndex("PrUrl");

                    b.HasIndex("Status");

                    b.HasIndex("WorkItemId");

                    b.HasIndex(new[] { "WorkItemId" }, "IX_LoopRuns_WorkItemId_Active")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (0, 4)");

                    b.ToTable("LoopRuns");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunAnalyticsBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiProvider")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("BucketDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CancelledRuns")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedRuns")
                        .HasColumnType("integer");

                    b.Property<int>("FailedRuns")
                        .HasColumnType("integer");

                    b.Property<int>("FeedbackCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("LoopTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("NodeCount")
                        .HasColumnType("integer");

                    b.Property<int>("OnFailureRoutings")
                        .HasColumnType("integer");

                    b.Property<int>("RejectRoutings")
                        .HasColumnType("integer");

                    b.Property<int>("RunCount")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("TotalCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<double>("TotalFeedbackSeconds")
                        .HasColumnType("double precision");

                    b.Property<long>("TotalInputTokens")
                        .HasColumnType("bigint");

                    b.Property<double>("TotalNodeSeconds")
                        .HasColumnType("double precision");

                    b.Property<long>("TotalOutputTokens")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BucketDate");

                    b.HasIndex("BucketDate", "LoopTemplateId", "AiProvider")
                        .IsUnique();

                    b.ToTable("LoopRunAnalyticsBuckets");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiProvider")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EffectiveInput")
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Guid?>("IncomingEdgeId")
                        .HasColumnType("uuid");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LoopNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoopRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("NodeLabel")
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("PreviousNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoopNodeId");

                    b.HasIndex("LoopRunId");

                    b.HasIndex("Status");

                    b.ToTable("LoopRunNodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunSessionBinding", b =>
                {
                    b.Property<Guid>("LoopRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PlaceholderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LoopRunId", "AdapterName", "PlaceholderId");

                    b.HasIndex("LoopRunId", "AdapterName", "SessionId");

                    b.ToTable("LoopRunSessionBindings");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunVariable", b =>
                {
                    b.Property<Guid>("LoopRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.HasKey("LoopRunId", "Name");

                    b.ToTable("LoopRunVariables");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunVariableWrite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("LoopRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<Guid?>("RunNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<DateTime>("WrittenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LoopRunId", "Name");

                    b.ToTable("LoopRunVariableWrites");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RecoveryPolicy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("LoopTemplates");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("LoopTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoopTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("LoopTemplateVersions");
                });

            modelBuilder.Entity("ILD.Data.Entities.NetworkForwardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<int>("LocalPort")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalPort")
                        .IsUnique();

                    b.ToTable("NetworkForwardEntries");
                });

            modelBuilder.Entity("ILD.Data.Entities.NetworkLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AiProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("NetworkLogEntries");
                });

            modelBuilder.Entity("ILD.Data.Entities.NetworkPolicyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AiProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<string>("ListKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AiProviderId");

                    b.HasIndex("ListKind", "Host", "AiProviderId")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ListKind", "Host", "AiProviderId"), false);

                    b.ToTable("NetworkPolicyEntries");
                });

            modelBuilder.Entity("ILD.Data.Entities.PackageFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Pat")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("PackageFeeds");
                });

            modelBuilder.Entity("ILD.Data.Entities.RemoteProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("RemoteProviders");
                });

            modelBuilder.Entity("ILD.Data.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("DefaultIntakeStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PreviewEnv")
                        .HasMaxLength(24576)
                        .HasColumnType("character varying(24576)");

                    b.Property<Guid>("RemoteProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorktreesPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RemoteProviderId");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("ILD.Data.Entities.RepositoryPackageFeed", b =>
                {
                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RepositoryId", "NormalizedName");

                    b.ToTable("RepositoryPackageFeeds");
                });

            modelBuilder.Entity("ILD.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ILD.Data.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedFromIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("ILD.Data.Entities.WorkItemStatusReason", b =>
                {
                    b.Property<string>("WorkItemId")
                        .HasColumnType("text");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkItemId");

                    b.ToTable("WorkItemStatusReasons");
                });

            modelBuilder.Entity("ILD.Data.Entities.AdapterSessionSnapshot", b =>
                {
                    b.HasOne("ILD.Data.Entities.ChatSession", "ChatSession")
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany()
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ChatSession");

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.AiProviderTag", b =>
                {
                    b.HasOne("ILD.Data.Entities.AiProvider", "AiProvider")
                        .WithMany("Tags")
                        .HasForeignKey("AiProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiProvider");
                });

            modelBuilder.Entity("ILD.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("ILD.Data.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("ILD.Data.Entities.ChatScheduleFiring", b =>
                {
                    b.HasOne("ILD.Data.Entities.ChatSession", null)
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ILD.Data.Entities.ChatSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ILD.Data.Entities.ChatSession", b =>
                {
                    b.HasOne("ILD.Data.Entities.ChatSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ILD.Data.Entities.EventLog", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany("EventLogs")
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNode", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopTemplateVersion", "LoopTemplateVersion")
                        .WithMany("Nodes")
                        .HasForeignKey("LoopTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopTemplateVersion");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNodeEdge", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopNode", "SourceNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ILD.Data.Entities.LoopNode", "TargetNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRun", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopTemplateVersion", "LoopTemplateVersion")
                        .WithMany("LoopRuns")
                        .HasForeignKey("LoopTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopTemplateVersion");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunNode", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopNode", "LoopNode")
                        .WithMany("RunNodes")
                        .HasForeignKey("LoopNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany("RunNodes")
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopNode");

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunSessionBinding", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany()
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunVariable", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany("Variables")
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRunVariableWrite", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopRun", "LoopRun")
                        .WithMany()
                        .HasForeignKey("LoopRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopRun");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplateVersion", b =>
                {
                    b.HasOne("ILD.Data.Entities.LoopTemplate", "LoopTemplate")
                        .WithMany("Versions")
                        .HasForeignKey("LoopTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoopTemplate");
                });

            modelBuilder.Entity("ILD.Data.Entities.NetworkPolicyEntry", b =>
                {
                    b.HasOne("ILD.Data.Entities.AiProvider", "AiProvider")
                        .WithMany()
                        .HasForeignKey("AiProviderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AiProvider");
                });

            modelBuilder.Entity("ILD.Data.Entities.Repository", b =>
                {
                    b.HasOne("ILD.Data.Entities.RemoteProvider", "RemoteProvider")
                        .WithMany("Repositories")
                        .HasForeignKey("RemoteProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemoteProvider");
                });

            modelBuilder.Entity("ILD.Data.Entities.RepositoryPackageFeed", b =>
                {
                    b.HasOne("ILD.Data.Entities.Repository", "Repository")
                        .WithMany("PackageFeeds")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("ILD.Data.Entities.UserSession", b =>
                {
                    b.HasOne("ILD.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ILD.Data.Entities.AiProvider", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ILD.Data.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopNode", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");

                    b.Navigation("RunNodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopRun", b =>
                {
                    b.Navigation("EventLogs");

                    b.Navigation("RunNodes");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ILD.Data.Entities.LoopTemplateVersion", b =>
                {
                    b.Navigation("LoopRuns");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("ILD.Data.Entities.RemoteProvider", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("ILD.Data.Entities.Repository", b =>
                {
                    b.Navigation("PackageFeeds");
                });
#pragma warning restore 612, 618
        }
    }
}
